name: Cypress Tests with Allure Report

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          npx cypress install  # Ensure Cypress is installed
          
      # Step 4: Set up Allure commandline
      - name: Set up Allure commandline
        run: npm install -g allure-commandline

      # Step 5: Install additional dependencies for Allure and Cypress
      - name: Install additional dependencies
        run: |
          npm install mocha-allure-reporter allure-cypress --save-dev
          npm install @bahmutov/cypress-esbuild-preprocessor @badeball/cypress-cucumber-preprocessor cypress-file-upload --save-dev

      # Step 6: Run Cypress tests and generate Allure results
      - name: Run Cypress tests
        run: |
          npx cypress run --reporter mocha-allure-reporter --reporter-options allureResults=allure-results
          echo "Cypress tests completed"

      # Step 7: Always generate Allure report, even if tests failed
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean
        if: always()

      # Step 8: Serve the Allure report locally
      - name: Serve Allure Report Locally
        run: |
          npm install -g http-server  # Install http-server
          http-server ./allure-report -p 8080 &
        # Note: You could use "nohup" if needed to run this in the background, e.g., `nohup http-server ./allure-report -p 8080 &`
        
      # Step 9: Optionally, Upload Allure report as artifact for easy access
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 30
