name: Run Cypress Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm ci  # Install dependencies from 'tests/package-lock.json'
          npx cypress install  # Install Cypress if not already installed

      # Step 4: Set up a Docker network for API server
      - name: Create Docker network
        run: |
          docker network create github_network_${{ github.run_id }}  # Create a user-defined network

      # Step 5: Start the API server in a Docker container
      - name: Start API Server
        run: |
          docker run -d --name api-server --network github_network_${{ github.run_id }} -p 7081:7081 \
            -e "SERVER_ADDRESS=0.0.0.0" openjdk:11 java -jar ./src/api/demo-0.0.1-SNAPSHOT.jar --server.address=0.0.0.0 --server.port=7081
          sleep 30  # Wait for 30 seconds to allow the server to start

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        run: |
          npx cypress run  # Run the Cypress tests

      # Step 7: Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: |
            ./allure-results/
            ./results/*.json

  generate-report:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Download test results
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: cypress-test-results
          path: results

      # Step 3: Generate Allure report
      - name: Generate Allure Report
        run: |
          allure generate results/cypress-test-results -o results/allure-report --clean

      # Step 4: Upload Allure report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: results/allure-report
          retention-days: 30
