name: Cypress Tests with Allure Report

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Inject environment variables from GitHub Secrets
      - name: Set environment variables from GitHub Secrets
        run: |
          echo "CYPRESS_baseUrl=${{ secrets.CYPRESS_baseUrl }}" >> $GITHUB_ENV
          echo "CYPRESS_baseUrlAPI=${{ secrets.CYPRESS_baseUrlAPI }}" >> $GITHUB_ENV
          echo "CYPRESS_allureResultsPath=${{ secrets.CYPRESS_allureResultsPath }}" >> $GITHUB_ENV

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          npx cypress install  # Ensure Cypress is installed

      # Step 5: Set up Allure commandline
      - name: Set up Allure commandline
        run: npm install -g allure-commandline

      # Step 6: Install additional dependencies for Allure and Cypress
      - name: Install additional dependencies
        run: |
          npm install mocha-allure-reporter allure-cypress --save-dev
          npm install @bahmutov/cypress-esbuild-preprocessor @badeball/cypress-cucumber-preprocessor cypress-file-upload --save-dev

      # Step 7: Run Cypress tests and generate Allure results
      - name: Run Cypress tests
        run: |
          npx cypress run --reporter mocha-allure-reporter --reporter-options allureResults=allure-results || true
          echo "Cypress tests completed (even with failures)"
          
      # Step 8: Generate Allure report (even if tests fail)
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean
        if: always()  # Ensures this step runs even if the previous step fails

      # Step 9: Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report  # Folder where the Allure report is generated
          publish_branch: gh-pages     # Deploy to gh-pages branch
        if: always()  # Ensures this step runs even if tests fail
